name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build PDF file
      run: ./build.sh --target pdf --docker build
    - name: Archive typesetting artifacts
      uses: actions/upload-artifact@v1
      with:
        name: PDF
        path: out/main.pdf
