name: Pandoc build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build PDF file
      run: |
        docker login -u publisher -p {{secrets.GITHUB_TOKEN}} docker.pkg.github.com
        ./build.sh --target pdf --docker --remote-image build
    - name: Archive typesetting artifacts
      uses: actions/upload-artifact@v1
      with:
        name: PDF
        path: out/main.pdf
